version: '3'
services:
  db:
    image: postgres
    container_name: server-side-quizz-db
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_DB
    volumes:
      - server-side-quizz-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    image: server-side-quizz
    container_name: server-side-quizz-board
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      - JWT_SECRET
    ports:
      - "8000:8000" 
    depends_on:
      - db 
volumes:
  node_modules:
  server-side-quizz-db-data:
